### ISSUE TITLE
GPL-641 As SSA (Louise Aigrain) I want to be able to relate failed Negative and Positive Controls to a Sample Type to monitor failure rates for each Sample Type [Heron]

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/wrangler#102]
**User story**
SSA's have a problem working out what sample type a positive or negative control is associated with. Controls themselves do not generally have a sample type, negative controls are water and positive controls known DNA fragments.
However they are added to plates or racks that only contain samples of one "Sample Type"

Currently controls released from CGaP all have a sample supplier id of the form "Negative control" or "Positive control...." that makes it difficult to relate the control back to the original CGaP sample plate and impossible to relate the control back to a given control batch.

**Who are the primary contacts for this story**
Louise Aigrain
Nicholas Redshaw
Matt Francis

**Acceptance criteria**
To be considered successful the solution must allow:
- The supplier id of a sample is picked up from the new _sample_identifier_ column in the _cgap_heron_ table for controls and sample. (For controls this will now contain a Mixtio barcode relating to the batch of control)
- To identify controls from the new _control_type_ column in the _cgap_heron_
- Note we do **NOT** need to patch any historic data for this story

**Dependencies**
This story is blocked by the following dependencies:
- GPL-578 in the CGaP Backlog needs to be released to production before this story is. (Currently this is released to UAT)

**Additional context**
More details here:
https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Relating+Controls+to+Sample+Type
https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/MLWH+cgap_heron+Table

**Comment by rl15** [comment]
Rich L wrote (Tuesday, 15 December 2020 at 14:44) 
Q> Does this backlog item still have high value to do?

**Comment by rl15** [comment]
Louse A wrote (Tuesday, 5 January 2021 at 11:30)

Hi Rich,
This is still very much of interest indeed as it’s a requirement for allowing to investigate failing controls. I understand the highest priority right now is the cherry-picking. I would suggest this should follow up shortly afterwards if possible.
Let me know if you (or Emma) have any question.
Best wishes,
Louise

**Comment by Skrich1999** [comment]
Emailed NIck and Louise to find out if this is still a relevant?

**Comment by Skrich1999** [comment]
Naomi Park - Definitely one to close!
