### ISSUE TITLE
GPL-441 Racks (or plates) flagged and released as Kestrel R&D put into an R&D study

### ISSUE THREAD

**Issue by rl15** [sanger/wrangler#41]
**User story**
GPL-441 | As SRA for CGaP (Laura) I want the study column in the cgap_heron table to be used to determine which SS study the samples go into. 

Reworded 15th May from

GPL-441 | As SRA for CGaP (Laura) I want to racks (or plates) flagged and released as Kestrel R&D to be put into an R&D study (#6TBD) in SS and not the production study (#6187) to separate the work for tracking & reporting

**Who the primary contacts are for this story**
Laura L (SRA CGaP)
Lesley S (Genomics R&D)

**Acceptance criteria**
TBD

**Comment by rl15** [comment]
Rich L wrote to R&D (Wednesday, 6 May 2020 at 10:36)

...

Q> Will you create a further study to track this work or will it be tracked in the existing R&D study #6198

Context
 
We are asking as today any releases from CGaP default to the production study 6187 
We can patch any releases in the short term to move samples between studies
We would like to make this automatic, so we need to understand if CGaP flag the material as Kestrel work what study the samples will be created in, 6198 or a new study?

**Comment by rl15** [comment]
“Project Kestrel” (study 6214) created on May 04, 2020 09:46

**Comment by KatyTaylor** [comment]
How will we identify from the data in the multi-LIMS warehouse that a sample is a Kestrel one?

**Comment by rl15** [comment]
Mapping of CGap projects to SS studies

Production:
??? > Study: Heron Project (6187) (Default?)
??? >  Study: Heron Project ONT (6191)
??? >  Study: Heron Project PacBio (6192)

R&D:
??? >  Study: Heron Project R & D (6198)
??? >  Study: Project Kestrel (6214)

**Comment by stevieing** [comment]
Closed as done
