### ISSUE TITLE
GPL-443 Release plates from CGaP while retaining option to release racks & rack tubes

### ISSUE THREAD

**Issue by rl15** [sanger/wrangler#42]
**User story**
GPL-443 | As SRA for CGaP (Laura) CGaP would like to release plates from CGaP, with a CGaP barcode as a process improvement while retaining option to release racks & rack tubes

**Who the primary contacts are for this story**
Laura L
Philip VV

**Acceptance criteria**
To be considered successful the solution must allow:
1. "Just like racks but with plates"
2. CGaP barcodes example: CGAP-3CEF2

**Additional context**

Backlog item in CGaP team also:  x489 | As an SRA (Laura) I want to be able to stamp into a plate (without individual well barcodes) as well as being able to stamp into the racks as we do currently - please keep all team in loop (also see output from retro email dated Tuesday, 5 May 2020 at 15:07)

**Comment by KatyTaylor** [comment]
Will these plates contain extracts, lysates, or could be either? Just thinking about what the 'plate purpose' should be.
