### ISSUE TITLE
GPL-478 samples released from CGAP to “CGAP extraction” to be created in SS

### ISSUE THREAD

**Issue by pjvv** [sanger/wrangler#47]
**User story**
As a CGAP SRA (Laura) who wants to use Samples Extraction, I want samples released from CGAP to “CGAP extraction” to be created in SS so I can scan them into Samples Extraction LIMS.

Details - I want the Wrangler to poll the `cgap_heron` MLWH table every ~ 2minutes for null in “Wrangled” column. When found the wrangler should create samples in SS with plate purpose TR stock 96 (for FluidX rack) or Stock plate (for plates) – only for samples where release destination is “CGAP extraction”. Once samples successfully created in SS, Wrangler enters time stamp into “Wrangled” column.

**Who the primary contacts are for this story**
Philip
Chris
Laura

**Acceptance criteria**
To be considered successful the solution must allow:
1. add a list of acceptance criteria here
2. ...

**Additional context**

**Comment by TWJW-SANGER** [comment]
depends-on: #43 (GPL-453) and  [GPL-496 in SequenceScape](https://github.com/sanger/sequencescape/issues/2700)

**Comment by TWJW-SANGER** [comment]
depends-on: #56

**Comment by pjvv** [comment]
depends-on: sanger/General-Backlog-Items#32
