### ISSUE TITLE
GPL-nnn Wrangler to create samples in SequenceScape with priority levels taken from CGaP

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/wrangler#79]
**User story**
As an SRA (Laura) I want a way to flag samples as priority so that they can be sequenced in duplicate and 'jump the queue' to be processed first.

**Who are the primary contacts for this story**
Laura Letchford <ll9@sanger.ac.uk>
Charlotte Beaver <cb29@sanger.ac.uk>
Richard Clark <rcc@sanger.ac.uk>
James Mack <jm36@sanger.ac.uk>

**Acceptance criteria**
- Sample Priority level to be read from cgap_heron table in MLWH
- Each sample created in SequenceScape must have it priority level set 
- It should not be possible under failure conditions to have samples created without the correct priorities (consider failures of requests to SequenceScape API, MLWH reads etc)

**Dependencies**
[CGaP Backlog x517](https://docs.google.com/spreadsheets/d/1vMDtA7N2jgjY3kvvh88nO7b4NpX769mSA8MUsS0YXPk/edit?usp=sharing)
[GPL-528](https://github.com/sanger/sequencescape/issues/2746)

**Additional context**
Link to overall prioritisation notes: 
https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Notes+on+Prioritisation+of+Heron+Samples

**Comment by pjvv** [comment]
Closed as there is no longer a coupling with CGAP.
